/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppExtratoRouteImport } from './routes/_app/extrato'
import { Route as AppGruposIndexRouteImport } from './routes/_app/grupos/index'
import { Route as AppGruposGroupIdRouteImport } from './routes/_app/grupos/$groupId'
import { Route as AppMeiosDePagamentoIndexRouteImport } from './routes/_app/meios-de-pagamento/index'
import { Route as AppMeiosDePagamentoMethodIdRouteImport } from './routes/_app/meios-de-pagamento/$methodId'
import { Route as AppSettingsPasswordRouteImport } from './routes/_app/settings/password'
import { Route as AppSettingsProfileRouteImport } from './routes/_app/settings/profile'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppExtratoRoute = AppExtratoRouteImport.update({
  id: '/extrato',
  path: '/extrato',
  getParentRoute: () => AppRoute,
} as any)
const AppGruposIndexRoute = AppGruposIndexRouteImport.update({
  id: '/grupos/',
  path: '/grupos/',
  getParentRoute: () => AppRoute,
} as any)
const AppGruposGroupIdRoute = AppGruposGroupIdRouteImport.update({
  id: '/grupos/$groupId',
  path: '/grupos/$groupId',
  getParentRoute: () => AppRoute,
} as any)
const AppMeiosDePagamentoIndexRoute =
  AppMeiosDePagamentoIndexRouteImport.update({
    id: '/meios-de-pagamento/',
    path: '/meios-de-pagamento/',
    getParentRoute: () => AppRoute,
  } as any)
const AppMeiosDePagamentoMethodIdRoute =
  AppMeiosDePagamentoMethodIdRouteImport.update({
    id: '/meios-de-pagamento/$methodId',
    path: '/meios-de-pagamento/$methodId',
    getParentRoute: () => AppRoute,
  } as any)
const AppSettingsPasswordRoute = AppSettingsPasswordRouteImport.update({
  id: '/settings/password',
  path: '/settings/password',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsProfileRoute = AppSettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/extrato': typeof AppExtratoRoute
  '/grupos/$groupId': typeof AppGruposGroupIdRoute
  '/meios-de-pagamento/$methodId': typeof AppMeiosDePagamentoMethodIdRoute
  '/settings/password': typeof AppSettingsPasswordRoute
  '/settings/profile': typeof AppSettingsProfileRoute
  '/grupos/': typeof AppGruposIndexRoute
  '/meios-de-pagamento/': typeof AppMeiosDePagamentoIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/extrato': typeof AppExtratoRoute
  '/': typeof AppIndexRoute
  '/grupos/$groupId': typeof AppGruposGroupIdRoute
  '/meios-de-pagamento/$methodId': typeof AppMeiosDePagamentoMethodIdRoute
  '/settings/password': typeof AppSettingsPasswordRoute
  '/settings/profile': typeof AppSettingsProfileRoute
  '/grupos': typeof AppGruposIndexRoute
  '/meios-de-pagamento': typeof AppMeiosDePagamentoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_app/extrato': typeof AppExtratoRoute
  '/_app/': typeof AppIndexRoute
  '/_app/grupos/$groupId': typeof AppGruposGroupIdRoute
  '/_app/meios-de-pagamento/$methodId': typeof AppMeiosDePagamentoMethodIdRoute
  '/_app/settings/password': typeof AppSettingsPasswordRoute
  '/_app/settings/profile': typeof AppSettingsProfileRoute
  '/_app/grupos/': typeof AppGruposIndexRoute
  '/_app/meios-de-pagamento/': typeof AppMeiosDePagamentoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/extrato'
    | '/grupos/$groupId'
    | '/meios-de-pagamento/$methodId'
    | '/settings/password'
    | '/settings/profile'
    | '/grupos/'
    | '/meios-de-pagamento/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/extrato'
    | '/'
    | '/grupos/$groupId'
    | '/meios-de-pagamento/$methodId'
    | '/settings/password'
    | '/settings/profile'
    | '/grupos'
    | '/meios-de-pagamento'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/signup'
    | '/_app/extrato'
    | '/_app/'
    | '/_app/grupos/$groupId'
    | '/_app/meios-de-pagamento/$methodId'
    | '/_app/settings/password'
    | '/_app/settings/profile'
    | '/_app/grupos/'
    | '/_app/meios-de-pagamento/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/extrato': {
      id: '/_app/extrato'
      path: '/extrato'
      fullPath: '/extrato'
      preLoaderRoute: typeof AppExtratoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/grupos/': {
      id: '/_app/grupos/'
      path: '/grupos'
      fullPath: '/grupos/'
      preLoaderRoute: typeof AppGruposIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/grupos/$groupId': {
      id: '/_app/grupos/$groupId'
      path: '/grupos/$groupId'
      fullPath: '/grupos/$groupId'
      preLoaderRoute: typeof AppGruposGroupIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/meios-de-pagamento/': {
      id: '/_app/meios-de-pagamento/'
      path: '/meios-de-pagamento'
      fullPath: '/meios-de-pagamento/'
      preLoaderRoute: typeof AppMeiosDePagamentoIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/meios-de-pagamento/$methodId': {
      id: '/_app/meios-de-pagamento/$methodId'
      path: '/meios-de-pagamento/$methodId'
      fullPath: '/meios-de-pagamento/$methodId'
      preLoaderRoute: typeof AppMeiosDePagamentoMethodIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/password': {
      id: '/_app/settings/password'
      path: '/settings/password'
      fullPath: '/settings/password'
      preLoaderRoute: typeof AppSettingsPasswordRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/profile': {
      id: '/_app/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AppSettingsProfileRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppExtratoRoute: typeof AppExtratoRoute
  AppIndexRoute: typeof AppIndexRoute
  AppGruposGroupIdRoute: typeof AppGruposGroupIdRoute
  AppMeiosDePagamentoMethodIdRoute: typeof AppMeiosDePagamentoMethodIdRoute
  AppSettingsPasswordRoute: typeof AppSettingsPasswordRoute
  AppSettingsProfileRoute: typeof AppSettingsProfileRoute
  AppGruposIndexRoute: typeof AppGruposIndexRoute
  AppMeiosDePagamentoIndexRoute: typeof AppMeiosDePagamentoIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppExtratoRoute: AppExtratoRoute,
  AppIndexRoute: AppIndexRoute,
  AppGruposGroupIdRoute: AppGruposGroupIdRoute,
  AppMeiosDePagamentoMethodIdRoute: AppMeiosDePagamentoMethodIdRoute,
  AppSettingsPasswordRoute: AppSettingsPasswordRoute,
  AppSettingsProfileRoute: AppSettingsProfileRoute,
  AppGruposIndexRoute: AppGruposIndexRoute,
  AppMeiosDePagamentoIndexRoute: AppMeiosDePagamentoIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
